"""Colour themes for the web UI.

Generated, not hand-picked. Each palette was built in OKLCH with roles assigned first
(canvas, surface, ink, action, alarm, data categories), chroma tapered near the lightness
extremes, then machine-checked: WCAG AA for text, 3:1 for the data swatches, plus two house
floors that stop a theme losing its edges -- card border >= 1.66:1 against the card, and card
>= 1.17:1 against the page. tests/test_home.py asserts all of it, so a new theme cannot ship
illegible.

A theme is a flat map of CSS custom properties; css() emits the [data-theme] blocks that
app.css consumes. Adding one means adding a dict here and nothing else.
"""
from __future__ import annotations

DEFAULT = "s1"

THEMES: dict[str, dict] = {
    "s1": {
        "label": 'Bone & Clay', "group": 'Soft',
        "note": 'P4a with the blood taken out: same bone canvas and espresso buttons, but the alarm softens from oxblood to clay',
        "tokens": {
            "accent": "#413129",
            "accent-hover": "#31231B",
            "accent-ink": "#F8F4F1",
            "archive": "#8D847E",
            "border": "#CFC4B7",
            "chip-bg": "#F6E8DF",
            "chip-ink": "#634632",
            "grain": "rgba(74,52,36,.05)",
            "ground": "#EFE9E1",
            "hero": "#3B2921",
            "hero-btn": "#F3EDE7",
            "hero-btn-hover": "#FFFEF8",
            "hero-btn-ink": "#3B2921",
            "hero-ink": "#F2EEE9",
            "hero-ink-2": "#B1A9A2",
            "hero-line": "#503E35",
            "hero-row": "#45332B",
            "ink": "#332924",
            "ink-2": "#716662",
            "ink-3": "#958D88",
            "likely": "#376441",
            "panel": "#F0E2D7",
            "rail": "#E7DED4",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFAF7",
            "reach": "#66508B",
            "row-hover": "#EFE9E1",
            "shadow": "rgba(74,52,36,.07)",
            "surface": "#FCFAF7",
            "warn": "#93412D",
            "warn-bg": "#FCE1D9",
            "warn-ink": "#893925",
            "warn-on": "#FCF7F5",
            "wildcard": "#9E7036",
        },
    },
    "s2": {
        "label": 'Oat & Moss', "group": 'Soft',
        "note": 'Warm oat canvas with a muted moss action — the button carries colour for once, but at half the chroma of pine',
        "tokens": {
            "accent": "#3A5D32",
            "accent-hover": "#2B4C24",
            "accent-ink": "#F6F9F6",
            "archive": "#8B857D",
            "border": "#CDC4B1",
            "chip-bg": "#E3EFE0",
            "chip-ink": "#35572D",
            "grain": "rgba(74,52,36,.05)",
            "ground": "#EEE9DE",
            "hero": "#313220",
            "hero-btn": "#3A5D32",
            "hero-btn-hover": "#476C3F",
            "hero-btn-ink": "#F6F9F6",
            "hero-ink": "#F1EEE9",
            "hero-ink-2": "#AEAAA1",
            "hero-line": "#464734",
            "hero-row": "#3B3C2A",
            "ink": "#302A21",
            "ink-2": "#6E685F",
            "ink-3": "#928F87",
            "likely": "#3A643B",
            "panel": "#F0E3D0",
            "rail": "#E6E0D0",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFAF6",
            "reach": "#66508B",
            "row-hover": "#EEE9DE",
            "shadow": "rgba(74,52,36,.07)",
            "surface": "#FCFAF6",
            "warn": "#994920",
            "warn-bg": "#FCE2D4",
            "warn-ink": "#8C3D12",
            "warn-on": "#FCF7F5",
            "wildcard": "#9E7036",
        },
    },
    "s3": {
        "label": 'Linen & Dusty Rose', "group": 'Soft',
        "note": 'A linen canvas with the faintest pink cast, taupe buttons and a dusty-rose alarm',
        "tokens": {
            "accent": "#493531",
            "accent-hover": "#382623",
            "accent-ink": "#FCF7F6",
            "archive": "#908785",
            "border": "#D4C2BE",
            "chip-bg": "#F8E7E3",
            "chip-ink": "#69453F",
            "grain": "rgba(74,52,36,.05)",
            "ground": "#F2E7E5",
            "hero": "#3D2B2A",
            "hero-btn": "#F5ECEA",
            "hero-btn-hover": "#FFFDFB",
            "hero-btn-ink": "#3D2B2A",
            "hero-ink": "#F4EDEB",
            "hero-ink-2": "#B6ABA9",
            "hero-line": "#533F3F",
            "hero-row": "#483534",
            "ink": "#362B2A",
            "ink-2": "#6B605F",
            "ink-3": "#908785",
            "likely": "#326445",
            "panel": "#F3DFDD",
            "rail": "#EBDCD9",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FDF9F8",
            "reach": "#665189",
            "row-hover": "#F2E7E5",
            "shadow": "rgba(74,52,36,.07)",
            "surface": "#FDF9F8",
            "warn": "#9C4E4F",
            "warn-bg": "#FFE4E3",
            "warn-ink": "#8F4244",
            "warn-on": "#FFFAFA",
            "wildcard": "#9F6F3D",
        },
    },
    "s4": {
        "label": 'Fog & Sage', "group": 'Soft',
        "note": 'The cool end of soft: a barely-green fog canvas with a sage action',
        "tokens": {
            "accent": "#2D6549",
            "accent-hover": "#1D533A",
            "accent-ink": "#F6F9F7",
            "archive": "#7E8988",
            "border": "#B9C8C4",
            "chip-bg": "#E0F0E7",
            "chip-ink": "#23593F",
            "grain": "rgba(40,58,56,.05)",
            "ground": "#E3EBE9",
            "hero": "#1E3231",
            "hero-btn": "#E9F0EE",
            "hero-btn-hover": "#FAFFFF",
            "hero-btn-ink": "#1E3231",
            "hero-ink": "#EBF0EE",
            "hero-ink-2": "#A3ADAA",
            "hero-line": "#324745",
            "hero-row": "#283C3B",
            "ink": "#232E2E",
            "ink-2": "#616B6C",
            "ink-3": "#899190",
            "likely": "#2A6549",
            "panel": "#D8E8E6",
            "rail": "#D6E3DF",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#F7FBFA",
            "reach": "#62528C",
            "row-hover": "#E3EBE9",
            "shadow": "rgba(40,58,56,.07)",
            "surface": "#F7FBFA",
            "warn": "#9B4630",
            "warn-bg": "#FCE1D9",
            "warn-ink": "#8E3A25",
            "warn-on": "#FCF7F5",
            "wildcard": "#9E6B36",
        },
    },
    "s5": {
        "label": 'Almond & Denim', "group": 'Soft',
        "note": 'Warm almond ground against a muted denim action — the only cool thing on a warm page, so the buttons read without shouting',
        "tokens": {
            "accent": "#365E86",
            "accent-hover": "#274D72",
            "accent-ink": "#F6F9FC",
            "archive": "#8C857D",
            "border": "#CFC4B4",
            "chip-bg": "#E2EDF8",
            "chip-ink": "#2D5277",
            "grain": "rgba(74,52,36,.05)",
            "ground": "#EFE9E0",
            "hero": "#242F3C",
            "hero-btn": "#F2EEE7",
            "hero-btn-hover": "#FFFEF8",
            "hero-btn-ink": "#242F3C",
            "hero-ink": "#F1EEEA",
            "hero-ink-2": "#AFAAA3",
            "hero-line": "#384351",
            "hero-row": "#2E3946",
            "ink": "#312A23",
            "ink-2": "#6F6761",
            "ink-3": "#948E88",
            "likely": "#306545",
            "panel": "#F1E2D4",
            "rail": "#E8DED2",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFAF6",
            "reach": "#62528C",
            "row-hover": "#EFE9E0",
            "shadow": "rgba(74,52,36,.07)",
            "surface": "#FCFAF6",
            "warn": "#9A482A",
            "warn-bg": "#FBE2D7",
            "warn-ink": "#8D3C1E",
            "warn-on": "#FCF7F5",
            "wildcard": "#9B6D32",
        },
    },
    "s6": {
        "label": 'Greige & Ochre', "group": 'Soft',
        "note": "Neutral greige canvas with a soft ochre action — citron's calmer cousin",
        "tokens": {
            "accent": "#A47F3E",
            "accent-hover": "#916E2E",
            "accent-ink": "#1F1401",
            "archive": "#8A857E",
            "border": "#CAC5B8",
            "chip-bg": "#F3EADB",
            "chip-ink": "#644B1E",
            "grain": "rgba(74,52,36,.05)",
            "ground": "#ECE9E2",
            "hero": "#362C21",
            "hero-btn": "#A47F3E",
            "hero-btn-hover": "#B48F4D",
            "hero-btn-ink": "#1F1401",
            "hero-ink": "#F0EEEA",
            "hero-ink-2": "#AEAAA2",
            "hero-line": "#4B4035",
            "hero-row": "#40362B",
            "ink": "#302A24",
            "ink-2": "#6E6862",
            "ink-3": "#928F88",
            "likely": "#376441",
            "panel": "#ECE3D8",
            "rail": "#E4DFD5",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FBFAF7",
            "reach": "#66518A",
            "row-hover": "#ECE9E2",
            "shadow": "rgba(74,52,36,.07)",
            "surface": "#FBFAF7",
            "warn": "#923B30",
            "warn-bg": "#FCE1DA",
            "warn-ink": "#883327",
            "warn-on": "#FCF7F6",
            "wildcard": "#A16E39",
        },
    },
    "p4a": {
        "label": 'Bone & Oxblood', "group": 'Editorial',
        "note": 'P4 with the same edge floors',
        "tokens": {
            "accent": "#38271C",
            "accent-hover": "#28190F",
            "accent-ink": "#F5F1EC",
            "archive": "#857B74",
            "border": "#CFC4B7",
            "chip-bg": "#F4E4DA",
            "chip-ink": "#5A3A23",
            "grain": "rgba(74,52,36,.055)",
            "ground": "#EFE9E1",
            "hero": "#281813",
            "hero-btn": "#F0EAE4",
            "hero-btn-hover": "#FFFBF5",
            "hero-btn-ink": "#281813",
            "hero-ink": "#EFEAE5",
            "hero-ink-2": "#A49D95",
            "hero-line": "#402E28",
            "hero-row": "#35241E",
            "ink": "#2D211C",
            "ink-2": "#665B56",
            "ink-3": "#8C847F",
            "likely": "#1B552C",
            "panel": "#F0E2D7",
            "rail": "#E7DED4",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFAF7",
            "reach": "#583A84",
            "row-hover": "#EFE9E1",
            "shadow": "rgba(74,52,36,.09)",
            "surface": "#FCFAF7",
            "warn": "#8B1E20",
            "warn-bg": "#FDDCD6",
            "warn-ink": "#85161B",
            "warn-on": "#FCF7F5",
            "wildcard": "#945A00",
        },
    },
    "p4b": {
        "label": 'Oxblood', "group": 'Editorial',
        "note": 'The other role assignment: oxblood becomes the button, and the alarm moves to a burnt amber',
        "tokens": {
            "accent": "#831A1D",
            "accent-hover": "#6D060F",
            "accent-ink": "#FCF8F4",
            "archive": "#857B74",
            "border": "#CFC4B7",
            "chip-bg": "#F4E4DA",
            "chip-ink": "#5A3A23",
            "grain": "rgba(74,52,36,.055)",
            "ground": "#EFE9E1",
            "hero": "#281813",
            "hero-btn": "#F0EAE4",
            "hero-btn-hover": "#FFFBF5",
            "hero-btn-ink": "#281813",
            "hero-ink": "#EFEAE5",
            "hero-ink-2": "#A49D95",
            "hero-line": "#402E28",
            "hero-row": "#35241E",
            "ink": "#2D211C",
            "ink-2": "#665B56",
            "ink-3": "#8C847F",
            "likely": "#1D5B30",
            "panel": "#F0E2D7",
            "rail": "#E7DED4",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFAF7",
            "reach": "#5E3F8C",
            "row-hover": "#EFE9E1",
            "shadow": "rgba(74,52,36,.09)",
            "surface": "#FCFAF7",
            "warn": "#9A3E00",
            "warn-bg": "#FAE4CC",
            "warn-ink": "#8B3400",
            "warn-on": "#FEFBF7",
            "wildcard": "#8D792A",
        },
    },
    "p6": {
        "label": 'Bone & Citron', "group": 'Editorial',
        "note": "The hybrid: P4's warm bone canvas with P3's citron action and oxblood kept for the alarm",
        "tokens": {
            "accent": "#C2B925",
            "accent-hover": "#AEA608",
            "accent-ink": "#201E00",
            "archive": "#857B74",
            "border": "#CFC4B7",
            "chip-bg": "#EAE9D3",
            "chip-ink": "#4D4700",
            "grain": "rgba(74,52,36,.055)",
            "ground": "#EFE9E1",
            "hero": "#281813",
            "hero-btn": "#C2B925",
            "hero-btn-hover": "#D2CA3D",
            "hero-btn-ink": "#201E00",
            "hero-ink": "#EFEAE5",
            "hero-ink-2": "#A49D95",
            "hero-line": "#402E28",
            "hero-row": "#35241E",
            "ink": "#2D211C",
            "ink-2": "#665B56",
            "ink-3": "#8C847F",
            "likely": "#195C2E",
            "panel": "#F0E2D7",
            "rail": "#E7DED4",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFAF7",
            "reach": "#5F3D8E",
            "row-hover": "#EFE9E1",
            "shadow": "rgba(74,52,36,.09)",
            "surface": "#FCFAF7",
            "warn": "#8B1E20",
            "warn-bg": "#FDDCD6",
            "warn-ink": "#85161B",
            "warn-on": "#FCF7F5",
            "wildcard": "#A16100",
        },
    },
    "p3a": {
        "label": 'Slate & Citron', "group": 'Cool',
        "note": 'P3 with edges made a role: borders tuned to 1',
        "tokens": {
            "accent": "#BCAE08",
            "accent-hover": "#A89B00",
            "accent-ink": "#1C1900",
            "archive": "#747B83",
            "border": "#C2CAD2",
            "chip-bg": "#DCEAF8",
            "chip-ink": "#0A4475",
            "grain": "rgba(28,38,58,.05)",
            "ground": "#E9EDF2",
            "hero": "#0E1720",
            "hero-btn": "#BCAE08",
            "hero-btn-hover": "#CCBE2C",
            "hero-btn-ink": "#1C1900",
            "hero-ink": "#ECEFF1",
            "hero-ink-2": "#999FA6",
            "hero-line": "#232C36",
            "hero-row": "#1A232C",
            "ink": "#192028",
            "ink-2": "#515961",
            "ink-3": "#7B8187",
            "likely": "#036639",
            "panel": "#E1E9F2",
            "rail": "#DEE4EA",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFEFF",
            "reach": "#50459E",
            "row-hover": "#E9EDF2",
            "shadow": "rgba(28,38,58,.09)",
            "surface": "#FCFEFF",
            "warn": "#AC3225",
            "warn-bg": "#FCE1D9",
            "warn-ink": "#9E2418",
            "warn-on": "#FEFBFA",
            "wildcard": "#A75C00",
        },
    },
    "p3b": {
        "label": 'Slate & Olive', "group": 'Cool',
        "note": 'The quiet reading of P3: the action goes deep olive with light type instead of bright citron',
        "tokens": {
            "accent": "#4E5D0E",
            "accent-hover": "#3F4C00",
            "accent-ink": "#F8F9F5",
            "archive": "#747B83",
            "border": "#C2CAD2",
            "chip-bg": "#E5EBD8",
            "chip-ink": "#414F00",
            "grain": "rgba(28,38,58,.05)",
            "ground": "#E9EDF2",
            "hero": "#0E1720",
            "hero-btn": "#EBEFF2",
            "hero-btn-hover": "#FCFFFF",
            "hero-btn-ink": "#0E1720",
            "hero-ink": "#ECEFF1",
            "hero-ink-2": "#999FA6",
            "hero-line": "#232C36",
            "hero-row": "#1A232C",
            "ink": "#192028",
            "ink-2": "#515961",
            "ink-3": "#7B8187",
            "likely": "#236436",
            "panel": "#E1E9F2",
            "rail": "#DEE4EA",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FCFEFF",
            "reach": "#50459E",
            "row-hover": "#E9EDF2",
            "shadow": "rgba(28,38,58,.09)",
            "surface": "#FCFEFF",
            "warn": "#AC3225",
            "warn-bg": "#FCE1D9",
            "warn-ink": "#9E2418",
            "warn-on": "#FEFBFA",
            "wildcard": "#A75C00",
        },
    },
    "p2": {
        "label": 'Paper & Pine', "group": 'Cool',
        "note": 'Light, warm-neutral, hierarchy-dominant, medium contrast, restrained',
        "tokens": {
            "accent": "#005C41",
            "accent-hover": "#00482F",
            "accent-ink": "#F6F9F8",
            "archive": "#83807A",
            "border": "#CBC7BD",
            "chip-bg": "#DEF0E7",
            "chip-ink": "#00563B",
            "grain": "rgba(62,54,40,.05)",
            "ground": "#F0EBE1",
            "hero": "#171913",
            "hero-btn": "#F0EEEA",
            "hero-btn-hover": "#FFFFFB",
            "hero-btn-ink": "#171913",
            "hero-ink": "#F0EEEB",
            "hero-ink-2": "#A19E99",
            "hero-line": "#2D2F28",
            "hero-row": "#23251E",
            "ink": "#24211B",
            "ink-2": "#66635D",
            "ink-3": "#8B8984",
            "likely": "#005C41",
            "panel": "#F2EEE7",
            "rail": "#EEEBE5",
            "rail-hover": "rgba(255,255,255,.62)",
            "rail-on": "#FEFDFC",
            "reach": "#593F91",
            "row-hover": "#F0EBE1",
            "shadow": "rgba(62,54,40,.08)",
            "surface": "#FEFDFC",
            "warn": "#9A3C00",
            "warn-bg": "#FBE7D8",
            "warn-ink": "#8D3000",
            "warn-on": "#FEFBF9",
            "wildcard": "#975800",
        },
    },
    "p1": {
        "label": 'Kinpaku', "group": 'Dark',
        "note": 'Dark, warm, atmosphere-dominant, high contrast, restrained dosage',
        "tokens": {
            "accent": "#FFB900",
            "accent-hover": "#EFA400",
            "accent-ink": "#271700",
            "archive": "#868686",
            "border": "#42403A",
            "chip-bg": "#0F2624",
            "chip-ink": "#6DCAC2",
            "grain": "rgba(255,250,235,.030)",
            "ground": "#080705",
            "hero": "#030202",
            "hero-btn": "#FFB900",
            "hero-btn-hover": "#FFCA00",
            "hero-btn-ink": "#271700",
            "hero-ink": "#E8E8E8",
            "hero-ink-2": "#9E9E9E",
            "hero-line": "#201F1B",
            "hero-row": "#0A0906",
            "ink": "#E1E1E1",
            "ink-2": "#A4A4A4",
            "ink-3": "#696969",
            "likely": "#0FB6AC",
            "panel": "#1A1511",
            "rail": "#100F0C",
            "rail-hover": "rgba(255,255,255,.07)",
            "rail-on": "#1C1B17",
            "reach": "#9896DA",
            "row-hover": "#080705",
            "shadow": "rgba(0,0,0,.50)",
            "surface": "#1C1B17",
            "warn": "#FC9252",
            "warn-bg": "#341E12",
            "warn-ink": "#FFCA9B",
            "warn-on": "#2B1401",
            "wildcard": "#F4A25C",
        },
    },
    "p5": {
        "label": 'Deep Teal & Coral', "group": 'Dark',
        "note": 'Dark, cool ground with warm sand type, atmosphere-dominant, immersive dosage',
        "tokens": {
            "accent": "#EC785B",
            "accent-hover": "#D5674C",
            "accent-ink": "#1E0804",
            "archive": "#818F90",
            "border": "#344D4E",
            "chip-bg": "#132F29",
            "chip-ink": "#78D1C0",
            "grain": "rgba(210,240,240,.035)",
            "ground": "#051C1E",
            "hero": "#000F10",
            "hero-btn": "#EC785B",
            "hero-btn-hover": "#FE886A",
            "hero-btn-ink": "#1E0804",
            "hero-ink": "#EEEBE4",
            "hero-ink-2": "#A8A49B",
            "hero-line": "#10282A",
            "hero-row": "#001517",
            "ink": "#EAE8E0",
            "ink-2": "#AEABA1",
            "ink-3": "#7D7A71",
            "likely": "#5FC199",
            "panel": "#011D1D",
            "rail": "#0C2628",
            "rail-hover": "rgba(255,255,255,.07)",
            "rail-on": "#122A2C",
            "reach": "#AAA0E6",
            "row-hover": "#051C1E",
            "shadow": "rgba(0,10,14,.45)",
            "surface": "#122A2C",
            "warn": "#F7AC4D",
            "warn-bg": "#36210E",
            "warn-ink": "#FFC47F",
            "warn-on": "#2B1401",
            "wildcard": "#F7AB5D",
        },
    },
}


def groups() -> list[tuple[str, list[tuple[str, dict]]]]:
    """Themes bucketed for the picker, in declaration order."""
    out: list[tuple[str, list[tuple[str, dict]]]] = []
    for key, t in THEMES.items():
        if not out or out[-1][0] != t["group"]:
            out.append((t["group"], []))
        out[-1][1].append((key, t))
    return out


def resolve(key: str | None) -> str:
    return key if key in THEMES else DEFAULT


def css() -> str:
    """`:root` carries the default; every theme also gets its own [data-theme] block."""
    blocks = []
    for key, t in THEMES.items():
        decls = "".join(f"  --{k}: {v};\n" for k, v in sorted(t["tokens"].items()))
        sel = ':root,\n[data-theme="%s"]' % key if key == DEFAULT else '[data-theme="%s"]' % key
        blocks.append(f"{sel} {{\n{decls}}}")
    return "\n".join(blocks) + "\n"
